name: tpotenv
dependencies:
  - python=3.4   # or 2.7
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - pip:
    - deap
    - update_checker
    - tqdm
    - stopit
    - xgboost
    - scikit-mdr
    - skrebate
    - tpot
